# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 0, 861, 691))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.canva_map = Mplwidget(self.tab_map)
        self.canva_map.setGeometry(QtCore.QRect(10, 10, 831, 511))
        self.canva_map.setObjectName("canva_map")
        self.tabWidget.addTab(self.tab_map, "")
        self.tab_pot = QtWidgets.QWidget()
        self.tab_pot.setObjectName("tab_pot")
        self.canva_pot = Mplwidget(self.tab_pot)
        self.canva_pot.setGeometry(QtCore.QRect(10, 10, 831, 511))
        self.canva_pot.setObjectName("canva_pot")
        self.tabWidget.addTab(self.tab_pot, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_takeoff = QtWidgets.QPushButton(self.widget)
        self.pushButton_takeoff.setObjectName("pushButton_takeoff")
        self.gridLayout.addWidget(self.pushButton_takeoff, 0, 0, 1, 1)
        self.pushButton_land = QtWidgets.QPushButton(self.widget)
        self.pushButton_land.setObjectName("pushButton_land")
        self.gridLayout.addWidget(self.pushButton_land, 0, 1, 1, 1)
        self.pushButton_centering = QtWidgets.QPushButton(self.widget)
        self.pushButton_centering.setObjectName("pushButton_centering")
        self.gridLayout.addWidget(self.pushButton_centering, 0, 2, 1, 1)
        self.pushButton_startMisison = QtWidgets.QPushButton(self.widget)
        self.pushButton_startMisison.setObjectName("pushButton_startMisison")
        self.gridLayout.addWidget(self.pushButton_startMisison, 0, 3, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map), _translate("MainWindow", "Map"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pot), _translate("MainWindow", "Potential"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_takeoff.setText(_translate("MainWindow", "Take Off"))
        self.pushButton_land.setText(_translate("MainWindow", "Land"))
        self.pushButton_centering.setText(_translate("MainWindow", "Centering"))
        self.pushButton_startMisison.setText(_translate("MainWindow", "Start Misison"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
from mplwidget import Mplwidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
